### ISSUE TITLE
DMCA file

### ISSUE THREAD

**Issue by zek-c** [futzumi/Big-Ideas-Math-Hack#1]
i have noticed you have stolen code from my repository [here](https://github.com/zek-c/swashbim), and if you do not remove this repository i  _WILL_ file a DMCA report and report your repository to github and have it forcefully removed. you have a weeks notice before i file a dmca report.

**Comment by futzumi** [comment]
Which one is stolen? i used a reference off of the infinite checks but there is litterally 5 other respitories who did the same

**Comment by zek-c** [comment]
it is the infinite checks. i created it around 2021 and ever since it circled around, so please remove it or delete the repo.

**Comment by futzumi** [comment]
Alright the the file is deleted. By the way, I looked at your repo and you dont have an answer hack. i reccomend making one

**Comment by zek-c** [comment]
the answer hack is in there, its modified from [flowingsalts repo](https://github.com/flowingsalt/bim-bot) its in the bookmarklets folder. you should check it out its a lot better than flowingsalts plain one. and yes i followed the reqs and read the license i can edit it. i plan to make my own, im sure it just fetches the button pressed (question you are on) and then uses getcurrentitem() from learnosity, and fetches answer that way. it is fairly simple

**Comment by zek-c** [comment]
i can admit i like they way you implemented enter to get answer
