### ISSUE TITLE
give me your discord

### ISSUE THREAD

**Issue by flowingsalt** [futzumi/Big-Ideas-Math-Hack#3]
bruh you are stealing my answer hack without credit rofl im gonna dmca this repo if you dont credit/contact me and continue to remove my issues.

**Comment by futzumi** [comment]
https://github.com/futzumi/Big-Ideas-Math-Hack/issues/2

**Comment by futzumi** [comment]
@flowingsalt add me when you can, ill send the unobfused code to you when i get your request. And when i prove it to you, im looking for to working on this hack with you
